[0m[[0m[0mdebug[0m] [0m[0m> Exec(__runWatch console0, Some(abfb69e8-d298-498c-b389-8e53d5b1a851), Some(CommandSource(console0)))[0m
[0m[[0m[0mdebug[0m] [0m[0m> Exec(sbtStashOnFailure, None, Some(CommandSource(console0)))[0m
[0m[[0m[0mdebug[0m] [0m[0m> Exec(__preWatch console0, None, Some(CommandSource(console0)))[0m
[0m[[0m[0mdebug[0m] [0m[0m> Exec(test, None, Some(CommandSource(console0)))[0m
[0m[[0m[0mdebug[0m] [0m[0mEvaluating tasks: Test / test[0m
[0m[[0m[0mdebug[0m] [0m[0mRunning task... Cancel: Signal, check cycles: false, forcegc: true[0m
[0m[[0m[0minfo[0m] [0m[0mcompiling 1 Scala source to /home/aryzach/Documents/Projects/Active/gitcloneinscalazio/target/scala-2.13/test-classes ...[0m
[0m[[0m[0minfo[0m] [0m[0m[32mRefDiscoveryTest:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- RefDiscovery.pktLine[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- RefDiscovery.gitProtoRequest[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m- RefDiscovery.lsRemote *** FAILED ***[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  "[]" did not equal "[IO[Remote]??????]" (RefDiscoveryTest.scala:13)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  Analysis:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  "[]" -> "[IO[Remote]??????]"[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m- RefDiscoverySpec[0m[0m
[0m[[0m[0minfo[0m] [0m[0m  [32m+[0m pktLine[0m
[0m[[0m[0minfo[0m] [0m[0m  [32m+[0m gitProtoRequest[0m
[0m[[0m[0minfo[0m] [0m[0m  [31m- lsRemote[0m[0m
[0m[[0m[0minfo[0m] [0m[0m    [34m`output` = [0m did not satisfy [36mequalTo(IO[Remote]??????)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m    [36mâ˜› /home/aryzach/Documents/Projects/Active/gitcloneinscalazio/src/test/scala/RefDiscoverySpec.scala:18[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[36mRan 3 tests in 1 s 679 ms: 2 succeeded, 0 ignored, 1 failed[0m[0m
[0m[[0m[0minfo[0m] [0m[0mScalaTest[0m
[0m[[0m[0minfo[0m] [0m[0m[36mRun completed in 4 seconds, 593 milliseconds.[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[36mTotal number of tests run: 3[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[36mSuites: completed 1, aborted 0[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[36mTests: succeeded 2, failed 1, canceled 0, ignored 0, pending 0[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m*** 1 TEST FAILED ***[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[4mZIO Test[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m- RefDiscoverySpec[0m[0m
[0m[[0m[0minfo[0m] [0m[0m  [31m- lsRemote[0m[0m
[0m[[0m[0minfo[0m] [0m[0m    [34m`output` = [0m did not satisfy [36mequalTo(IO[Remote]??????)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m    [36mâ˜› /home/aryzach/Documents/Projects/Active/gitcloneinscalazio/src/test/scala/RefDiscoverySpec.scala:18[0m[0m
[0m[[0m[0minfo[0m] [0m[0mDone[0m
[0m[[0m[31merror[0m] [0m[0mFailed: Total 6, Failed 2, Errors 0, Passed 4[0m
[0m[[0m[31merror[0m] [0m[0mFailed tests:[0m
[0m[[0m[31merror[0m] [0m[0m	RefDiscoveryTest[0m
[0m[[0m[31merror[0m] [0m[0m	RefDiscoverySpec[0m
[0m[[0m[0mdebug[0m] [0m[0mForcing garbage collection...[0m
[0m[[0m[31merror[0m] [0m[0m(Test / [31mtest[0m) sbt.TestsFailedException: Tests unsuccessful[0m
[0m[[0m[31merror[0m] [0m[0mTotal time: 7 s, completed Aug 30, 2021, 5:36:28 PM[0m
[0m[[0m[0mdebug[0m] [0m[0m> Exec(resumeFromFailure, None, Some(CommandSource(console0)))[0m
[0m[[0m[0mdebug[0m] [0m[0m> Exec(sbtPopOnFailure, None, Some(CommandSource(console0)))[0m
[0m[[0m[0mdebug[0m] [0m[0m> Exec(__postWatch console0, None, Some(CommandSource(console0)))[0m
[0m[[0m[0mdebug[0m] [0m[0m> Exec(resumeFromFailure, None, None)[0m
[0m[[0m[0mdebug[0m] [0m[0m> Exec(__waitWatch console0, None, None)[0m
